name: fastapi
on:
    push:
        branches:
            - main
jobs:
    build-and-push:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - run: pip install poetry==2.1.2
            - run: poetry install
            - run: poetry run flake8
            - run: poetry run pytest